#!/bin/sh
#SBATCH --job-name=gr
#SBATCH --output=gr.log
#SBATCH --error=gr.serr
#SBATCH --partition=savio
#SBATCH --time=4:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=20
# QoS:
#SBATCH --qos=nuclear_savio_normal
# Account:
#SBATCH -A co_nuclear

# Mail type:
#SBATCH --mail-type=all
#
# Mail user:
#SBATCH --mail-user=imwangxin@gmail.com
module load intel
module load openmpi/1.6.5-intel

sss2 -omp 20 serp_full_core
